# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import restaurant_service_pb2 as restaurant__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in restaurant_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RestaurantServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRestaurant = channel.unary_unary(
                '/restaurant.RestaurantService/GetRestaurant',
                request_serializer=restaurant__service__pb2.GetRestaurantRequest.SerializeToString,
                response_deserializer=restaurant__service__pb2.RestaurantResponse.FromString,
                _registered_method=True)
        self.UpdateMenu = channel.unary_unary(
                '/restaurant.RestaurantService/UpdateMenu',
                request_serializer=restaurant__service__pb2.UpdateMenuRequest.SerializeToString,
                response_deserializer=restaurant__service__pb2.MenuResponse.FromString,
                _registered_method=True)
        self.GetRestaurantPayments = channel.unary_unary(
                '/restaurant.RestaurantService/GetRestaurantPayments',
                request_serializer=restaurant__service__pb2.GetRestaurantPaymentsRequest.SerializeToString,
                response_deserializer=restaurant__service__pb2.GetRestaurantPaymentsResponse.FromString,
                _registered_method=True)


class RestaurantServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRestaurant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRestaurantPayments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaurantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRestaurant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRestaurant,
                    request_deserializer=restaurant__service__pb2.GetRestaurantRequest.FromString,
                    response_serializer=restaurant__service__pb2.RestaurantResponse.SerializeToString,
            ),
            'UpdateMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMenu,
                    request_deserializer=restaurant__service__pb2.UpdateMenuRequest.FromString,
                    response_serializer=restaurant__service__pb2.MenuResponse.SerializeToString,
            ),
            'GetRestaurantPayments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRestaurantPayments,
                    request_deserializer=restaurant__service__pb2.GetRestaurantPaymentsRequest.FromString,
                    response_serializer=restaurant__service__pb2.GetRestaurantPaymentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'restaurant.RestaurantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('restaurant.RestaurantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RestaurantService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRestaurant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/GetRestaurant',
            restaurant__service__pb2.GetRestaurantRequest.SerializeToString,
            restaurant__service__pb2.RestaurantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/UpdateMenu',
            restaurant__service__pb2.UpdateMenuRequest.SerializeToString,
            restaurant__service__pb2.MenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRestaurantPayments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/GetRestaurantPayments',
            restaurant__service__pb2.GetRestaurantPaymentsRequest.SerializeToString,
            restaurant__service__pb2.GetRestaurantPaymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
