# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: restaurant_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'restaurant_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18restaurant_service.proto\x12\nrestaurant\"-\n\x14GetRestaurantRequest\x12\x15\n\rrestaurant_id\x18\x01 \x01(\t\"\x85\x01\n\x12RestaurantResponse\x12\x15\n\rrestaurant_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x0f\n\x07is_open\x18\x04 \x01(\x08\x12(\n\nmenu_items\x18\x05 \x03(\x0b\x32\x14.restaurant.MenuItem\"T\n\x11UpdateMenuRequest\x12\x15\n\rrestaurant_id\x18\x01 \x01(\t\x12(\n\nmenu_items\x18\x02 \x03(\x0b\x32\x14.restaurant.MenuItem\"`\n\x08MenuItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x11\n\tavailable\x18\x05 \x01(\x08\"c\n\x0cMenuResponse\x12\x15\n\rrestaurant_id\x18\x01 \x01(\t\x12(\n\nmenu_items\x18\x02 \x03(\x0b\x32\x14.restaurant.MenuItem\x12\x12\n\nupdated_at\x18\x03 \x01(\t\"5\n\x1cGetRestaurantPaymentsRequest\x12\x15\n\rrestaurant_id\x18\x01 \x01(\t\"b\n\x07Payment\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"F\n\x1dGetRestaurantPaymentsResponse\x12%\n\x08payments\x18\x01 \x03(\x0b\x32\x13.restaurant.Payment2\x9b\x02\n\x11RestaurantService\x12Q\n\rGetRestaurant\x12 .restaurant.GetRestaurantRequest\x1a\x1e.restaurant.RestaurantResponse\x12\x45\n\nUpdateMenu\x12\x1d.restaurant.UpdateMenuRequest\x1a\x18.restaurant.MenuResponse\x12l\n\x15GetRestaurantPayments\x12(.restaurant.GetRestaurantPaymentsRequest\x1a).restaurant.GetRestaurantPaymentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'restaurant_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETRESTAURANTREQUEST']._serialized_start=40
  _globals['_GETRESTAURANTREQUEST']._serialized_end=85
  _globals['_RESTAURANTRESPONSE']._serialized_start=88
  _globals['_RESTAURANTRESPONSE']._serialized_end=221
  _globals['_UPDATEMENUREQUEST']._serialized_start=223
  _globals['_UPDATEMENUREQUEST']._serialized_end=307
  _globals['_MENUITEM']._serialized_start=309
  _globals['_MENUITEM']._serialized_end=405
  _globals['_MENURESPONSE']._serialized_start=407
  _globals['_MENURESPONSE']._serialized_end=506
  _globals['_GETRESTAURANTPAYMENTSREQUEST']._serialized_start=508
  _globals['_GETRESTAURANTPAYMENTSREQUEST']._serialized_end=561
  _globals['_PAYMENT']._serialized_start=563
  _globals['_PAYMENT']._serialized_end=661
  _globals['_GETRESTAURANTPAYMENTSRESPONSE']._serialized_start=663
  _globals['_GETRESTAURANTPAYMENTSRESPONSE']._serialized_end=733
  _globals['_RESTAURANTSERVICE']._serialized_start=736
  _globals['_RESTAURANTSERVICE']._serialized_end=1019
# @@protoc_insertion_point(module_scope)
