# docker compose file for the inspired food platform

services:
  # order service 
  order_service:
    build:
      context: .
      dockerfile: order_service/Order.Dockerfile
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
    networks:
      - food-network
    restart: on-failure

  # delivery service
  delivery_service:
    build:
      context: .
      dockerfile: delivery_service/Delivery.Dockerfile
    ports:
      - "50052:50052"
    environment:
      - PORT=50052
      - ORDER_SERVICE_ADDR=order_service:50051
    networks:
      - food-network
    depends_on:
      - order_service
    restart: on-failure

  # restaurant service
  restaurant_service:
    build:
      context: .
      dockerfile: restaurant_service/Restaurant.Dockerfile
    ports:
      - "50053:50053"
    environment:
      - PORT=50053
    networks:
      - food-network
    restart: on-failure

  # api gateway
  api_gateway:
    build:
      context: .
      dockerfile: gateway/Gateway.Dockerfile
    ports:
      - "50050:50050"
    environment:
      - PORT=50050
      - ORDER_SERVICE_ADDR=order_service:50051
      - DELIVERY_SERVICE_ADDR=delivery_service:50052
      - RESTAURANT_SERVICE_ADDR=restaurant_service:50053
    networks:
      - food-network
    depends_on:
      - order_service
      - delivery_service
      - restaurant_service
    restart: on-failure

  # client
  client:
    build:
      context: .
      dockerfile: client/Client.Dockerfile
    environment:
      - API_GATEWAY_HOST=api_gateway
      - API_GATEWAY_PORT=50050
    networks:
      - food-network
    depends_on:
      - api_gateway
    restart: on-failure

networks:
  food-network:
    driver: bridge