# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: customer_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'customer_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ustomer_service.proto\x12\x08\x63ustomer\")\n\x12GetCustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\"t\n\x15UpdateCustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x1a\n\x12\x64\x65livery_addresses\x18\x05 \x03(\t\"o\n\x10\x43ustomerResponse\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x1a\n\x12\x64\x65livery_addresses\x18\x05 \x03(\t2\xa9\x01\n\x0f\x43ustomerService\x12G\n\x0bGetCustomer\x12\x1c.customer.GetCustomerRequest\x1a\x1a.customer.CustomerResponse\x12M\n\x0eUpdateCustomer\x12\x1f.customer.UpdateCustomerRequest\x1a\x1a.customer.CustomerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCUSTOMERREQUEST']._serialized_start=36
  _globals['_GETCUSTOMERREQUEST']._serialized_end=77
  _globals['_UPDATECUSTOMERREQUEST']._serialized_start=79
  _globals['_UPDATECUSTOMERREQUEST']._serialized_end=195
  _globals['_CUSTOMERRESPONSE']._serialized_start=197
  _globals['_CUSTOMERRESPONSE']._serialized_end=308
  _globals['_CUSTOMERSERVICE']._serialized_start=311
  _globals['_CUSTOMERSERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
